[package]
edition = "2024"
name = "envelope-generator"
version = "0.1.0"
license = "MIT"
publish = false

[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "defmt",
  "time-driver-any",
  "stm32g0b1ce",
  "memory-x",
  "unstable-pac",
  "exti",
  "chrono",
] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "defmt",
] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "platform-cortex-m",
  "executor-thread",
  "defmt",
] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab", features = [
  "defmt",
  "defmt-timestamp-uptime",
  "tick-hz-32_768",
] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "26ad6ec71de3d55e5cbc04a72d7174185f3e86ab" }
defmt = "1.0.1"
defmt-rtt = "1.0.0"

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.6"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
heapless = { version = "0.9", default-features = false }
chrono = { version = "^0.4", default-features = false }
embedded-can = "0.4"
static_cell = "2.1.1"
portable-atomic = { version = "1.13.0", features = ["critical-section"] }
num_enum = { version = "0.7.5", default-features = false }
analog3 = { path = "../../analog3", features = ["stm32g0b1ce"] }
ssd1306-lite = { path = "../../ssd1306-lite" }
embedded-graphics = { git = "https://github.com/naokiiwakami/embedded-graphics.git", tag = "embedded-graphics-v0.8.2-fork" }

[profile.release]
debug = 2
opt-level = "s"
lto = true

[package.metadata.embassy]
build = [{ target = "thumbv6m-none-eabi", artifact-dir = "out" }]

[features]
default = []
# optionally enables bit rate switching in CAN tx
bit-rate-switching = []
